---
title: "tidy_data"
author: "Ziqing Wang"
date: "2022-09-27"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)
options(tibble.print_min = 5)
```

# pivot_longer()
```{r}
pulse_df = haven::read_sas("./data/public_pulse_data.sas7bdat") %>% 
  janitor::clean_names()
pulse_df
```

```{r}
pulse_tidy_data = 
  pivot_longer(pulse_df,
               bdi_score_bl:bdi_score_12m,
               names_to = "visit",
               names_prefix = "bdi_score_",
               values_to = "bdi")
pulse_tidy_data
```

Usually saving intermediate data frames, although is a good way to test whether your code works, is often not a good practice. The following code transforms the originical data to tidy data all together:

```{r}
pulse_df = 
  haven::read_sas("./data/public_pulse_data.sas7bdat") %>%
  janitor::clean_names() %>%
  pivot_longer(
    bdi_score_bl:bdi_score_12m,
    names_to = "visit", 
    names_prefix = "bdi_score_",
    values_to = "bdi") %>%
  relocate(visit) %>%
  mutate(
    visit = replace(visit, visit == "bl", "00m"),
    visit = factor(visit)) %>%
  arrange(id, visit)

print(pulse_df, n = 12)
```
# practoce pivot_longer()
```{r}
litter_tidy_data = read_csv("./data/FAS_litters.csv") %>% 
  janitor::clean_names() %>%
  #select(litter_number, gd0_weight, gd18_weight) %>% 
  select(litter_number, ends_with("weight")) %>% 
  pivot_longer(gd0_weight:gd18_weight,
               names_to = "gd",
               values_to = "weight") %>%
  mutate(gd = recode(gd, "gd0_weight" = 0, "gd18_weight" = 18))

litter_tidy_data
```


# pivot_wider
```{r}
analysis_result = tibble(
  group = c("treatment", "treatment", "placebo", "placebo"),
  time = c("pre", "post", "pre", "post"),
  mean = c(4, 8, 3.5, 4)
)

analysis_result
```

```{r}
pivot_wider(analysis_result, names_from = "time", values_from = "mean")
```

#  binding rows
```{r}
fellowship_ring = 
  readxl::read_excel("./data/LotR_Words.xlsx", range = "B3:D6") %>%
  mutate(movie = "fellowship_ring")

two_towers = 
  readxl::read_excel("./data/LotR_Words.xlsx", range = "F3:H6") %>%
  mutate(movie = "two_towers")

return_king = 
  readxl::read_excel("./data/LotR_Words.xlsx", range = "J3:L6") %>%
  mutate(movie = "return_king")

fellowship_ring
two_towers
return_king
```

```{r}
lotr_tidy = bind_rows(fellowship_ring, two_towers, return_king) %>%
  janitor::clean_names() %>%
  pivot_longer(female:male,
               names_to = "gender",
               values_to = "word") %>%
  mutate(race = str_to_lower(race)) %>%
  select(movie, everything())
lotr_tidy
```

# joining data frames

```{r}
pup_data = 
  read_csv("./data/FAS_pups.csv") %>%
  janitor::clean_names() %>%
  mutate(
    sex = recode(sex, `1` = "male", `2` = "female"),
    sex = factor(sex)) 

litter_data = 
  read_csv("./data/FAS_litters.csv") %>%
  janitor::clean_names() %>%
  separate(group, into = c("dose", "day_of_tx"), sep = 3) %>%
  relocate(litter_number) %>%
  mutate(
    wt_gain = gd18_weight - gd0_weight,
    dose = str_to_lower(dose))

fas_data = 
  left_join(pup_data, litter_data, by = "litter_number")

pup_data # baby data
litter_data # mother data
fas_data
```

```{r}
os_data = read_csv("./data/survey_results/surv_os.csv") %>%
  janitor::clean_names()

git_data = read_csv("./data/survey_results/surv_program_git.csv") %>%
  janitor::clean_names()

exp_data = left_join(os_data, git_data, by = "what_is_your_uni")

os_data
git_data
exp_data
```


Practice with inner_join and anti_join as well

